"""
Phase 8: Database & Production Backend - Alembic Migrations & Indexing
================================================================================
1. CONCEPT & JS/TS ANALOGY:
   - Alembic is the official database migration tool for SQLAlchemy.
   - Core Workflow:
     1. 'alembic init -t async migrations': Initializes migration directory with async support.
     2. 'alembic revision --autogenerate -m "Add index to email"': Inspects models against live DB.
     3. 'alembic upgrade head': Applies all pending forward migrations.
     4. 'alembic downgrade -1': Reverts the latest migration safely.
   - Production PostgreSQL Indexing Strategies:
     * B-Tree Indexes: Standard index for '=', '<', '>', 'BETWEEN', and 'LIKE "prefix%"'.
     * Composite Indexes: Multiple columns (e.g. '(tenant_id, created_at)').
       - The Leftmost Prefix Rule: An index on (A, B) accelerates queries on A, and queries on (A, B),
         but CANNOT be used for queries filtering only on B!
     * Partial Indexes: 'CREATE INDEX idx_active_users ON users(email) WHERE is_active = true;'.
       Reduces index size dramatically by only indexing rows matching a condition.
     * Unique Constraints vs Unique Indexes: In PostgreSQL, unique constraints automatically create a unique B-Tree index.
   - JS/TS Analogy:
     * Prisma Migrate ('prisma migrate dev' / 'prisma db push') vs Alembic.
     * Knex.js migrations vs Alembic migration scripts.

2. UNDER THE HOOD (CPython & Memory):
   - Alembic autogenerate compares Python 'MetaData' objects with PostgreSQL's 'information_schema'.
   - Limitation: Autogenerate cannot detect table or column renames! It sees a rename as dropping
     the old column and adding a new column, which will DESTROY production data if executed blindly.

3. COMMON GOTCHA:
   - Blindly running autogenerated migrations without manual review. Always inspect the generated
     file in 'migrations/versions/' before executing on staging or production!
   - Forgetting to import entity models in 'migrations/env.py': If models aren't imported, Alembic
     sees an empty MetaData and generates scripts that DROP ALL TABLES in your database!

4. 🎙️ INTERVIEW READINESS: VERBAL RESPONSE SCRIPT
   -----------------------------------------------------------------------------
   Q: "How does Alembic autogenerate migrations, what are its critical limitations,
       and how do you design indexing strategies in PostgreSQL?"
   
   HOW TO ANSWER OUT LOUD (60-90 sec script):
   1. Alembic Architecture & Autogenerate:
      "Alembic operates by comparing the SQLAlchemy MetaData registry in Python against the live
       database schema queried from PostgreSQL's information_schema.
       When we run 'alembic revision --autogenerate', it produces a Python script with 'upgrade()'
       and 'downgrade()' functions containing DDL operations (op.create_table, op.add_column)."
   2. Critical Limitations & Safety:
      "Autogenerate is powerful but dangerous if unreviewed:
       First, it cannot distinguish a column rename from a DROP column + ADD column. Running it
       blindly will cause permanent data loss.
       Second, it doesn't automatically detect changes in table constraints or server defaults.
       In CI/CD, migration scripts must be peer-reviewed and tested against shadow databases before promotion."
   3. Indexing Strategies (Leftmost Prefix & Partial Indexes):
      "When indexing for high-scale PostgreSQL workloads:
       - For composite indexes (e.g. tenant_id, status, created_at), we order columns from highest
         equality cardinality to range filters, respecting the Leftmost Prefix Rule.
       - We leverage Partial Indexes with WHERE clauses (e.g. indexing only unresolved alerts or active users)
         to drastically reduce index RAM usage and keep hot index pages resident in PostgreSQL buffer cache."
================================================================================
"""

import sys
from sqlalchemy import Column, Integer, String, Index, Table, MetaData

# Ensure UTF-8 output encoding across Windows terminals
if sys.stdout.encoding and sys.stdout.encoding.lower() != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass


metadata = MetaData()

users_table = Table(
    "accounts",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("tenant_id", Integer, nullable=False),
    Column("email", String(100), nullable=False),
    Column("status", String(20), default="ACTIVE"),
    Index("idx_tenant_status", "tenant_id", "status"),
    Index("idx_unique_active_email", "email", unique=True, postgresql_where=(Column("status") == "ACTIVE"))
)


def demonstrate_alembic_script_structure():
    print("\n--- 1. Structure of an Alembic Migration Script ---")
    script_text = (
        "# Revision: 7a8b9c0d1e2f\n"
        "from alembic import op\n"
        "import sqlalchemy as sa\n\n"
        "def upgrade():\n"
        "    op.create_table('accounts',\n"
        "        sa.Column('id', sa.Integer(), primary_key=True),\n"
        "        sa.Column('tenant_id', sa.Integer(), nullable=False),\n"
        "        sa.Column('email', sa.String(100), nullable=False)\n"
        "    )\n"
        "    op.create_index('idx_tenant', 'accounts', ['tenant_id'])\n\n"
        "def downgrade():\n"
        "    op.drop_index('idx_tenant', table_name='accounts')\n"
        "    op.drop_table('accounts')\n"
    )
    print(script_text)


def demonstrate_leftmost_prefix_rule():
    print("\n--- 2. Leftmost Prefix Rule Explanation ---")
    print("  Composite Index: (tenant_id, status, created_at)")
    queries = [
        ("WHERE tenant_id = 5", True, "Uses index (Leftmost prefix match)"),
        ("WHERE tenant_id = 5 AND status = 'ACTIVE'", True, "Uses index (2-column prefix match)"),
        ("WHERE tenant_id = 5 AND created_at > '2026-01-01'", True, "Uses index on tenant_id, then filters created_at"),
        ("WHERE status = 'ACTIVE'", False, "CANNOT use index! Missing leftmost column 'tenant_id'"),
        ("WHERE created_at > '2026-01-01'", False, "CANNOT use index! Full table scan required"),
    ]
    for q, can_use, explanation in queries:
        status_icon = "✅" if can_use else "❌"
        print(f"  {status_icon} Query: {q:<48} -> {explanation}")


def can_query_use_composite_index(index_cols: list[str], query_filter_cols: list[str]) -> bool:
    if not query_filter_cols or not index_cols:
        return False
    return index_cols[0] in query_filter_cols


def run_tests():
    print("\n[*] Running automated tests for 02_alembic_migrations_and_indexing.py...")
    idx = ["tenant_id", "status", "created_at"]
    
    assert can_query_use_composite_index(idx, ["tenant_id"]) is True
    assert can_query_use_composite_index(idx, ["tenant_id", "status"]) is True
    assert can_query_use_composite_index(idx, ["tenant_id", "created_at"]) is True
    assert can_query_use_composite_index(idx, ["status", "created_at"]) is False
    assert can_query_use_composite_index(idx, ["created_at"]) is False
    assert can_query_use_composite_index(idx, []) is False

    print("[SUCCESS] All Alembic & Indexing tests passed cleanly!")


if __name__ == "__main__":
    print("=" * 65)
    print("Execution: Phase 8 - Alembic Migrations & Indexing Strategies")
    print("=" * 65)
    demonstrate_alembic_script_structure()
    demonstrate_leftmost_prefix_rule()
    print("-" * 65)
    run_tests()
    print("=" * 65)
